"""service records, reminders, notifications

Revision ID: 5aa88876da4e
Revises: 74010ff95bc3
Create Date: 2026-07-17 19:04:18.217830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '5aa88876da4e'
down_revision: Union[str, None] = '74010ff95bc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('config', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_channels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_channels_user_id'), ['user_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('dedupe_key', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_dedupe_key'), ['dedupe_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('service_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('odometer', sa.Float(), nullable=True),
    sa.Column('shop', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('is_diy', sa.Boolean(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_records_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_records_vehicle_id'), ['vehicle_id'], unique=False)

    op.create_table('service_reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('interval_miles', sa.Float(), nullable=True),
    sa.Column('interval_months', sa.Float(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('due_odometer', sa.Float(), nullable=True),
    sa.Column('last_done_date', sa.DateTime(), nullable=True),
    sa.Column('last_done_odometer', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_reminders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_reminders_vehicle_id'), ['vehicle_id'], unique=False)

    op.create_table('service_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('service_type', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('parts', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['service_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_items_record_id'), ['record_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_items_record_id'))

    op.drop_table('service_items')
    with op.batch_alter_table('service_reminders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_reminders_vehicle_id'))

    op.drop_table('service_reminders')
    with op.batch_alter_table('service_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_records_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_service_records_date'))

    op.drop_table('service_records')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_dedupe_key'))

    op.drop_table('notifications')
    with op.batch_alter_table('notification_channels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_channels_user_id'))

    op.drop_table('notification_channels')
    # ### end Alembic commands ###
