"""fuel-ups, charge sessions, odometer adjustments, tags

Revision ID: 74010ff95bc3
Revises: ee2e568bfa33
Create Date: 2026-07-17 17:08:04.284883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '74010ff95bc3'
down_revision: Union[str, None] = 'ee2e568bfa33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tags_owner_id'), ['owner_id'], unique=False)

    op.create_table('charge_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('odometer', sa.Float(), nullable=False),
    sa.Column('kwh_added', sa.Float(), nullable=False),
    sa.Column('price_per_kwh', sa.Float(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('fill_type', sa.Enum('full', 'partial', 'missed', name='filltype'), nullable=False),
    sa.Column('charge_type', sa.Enum('home', 'public_l2', 'dc_fast', name='chargetype'), nullable=False),
    sa.Column('start_pct', sa.Float(), nullable=True),
    sa.Column('end_pct', sa.Float(), nullable=True),
    sa.Column('station', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('charge_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_charge_sessions_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_charge_sessions_vehicle_id'), ['vehicle_id'], unique=False)

    op.create_table('fuelups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('odometer', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('price_per_unit', sa.Float(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('fill_type', sa.Enum('full', 'partial', 'missed', name='filltype'), nullable=False),
    sa.Column('fuel_grade', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('station', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fuelups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fuelups_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_fuelups_vehicle_id'), ['vehicle_id'], unique=False)

    op.create_table('odometer_adjustments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('old_odometer', sa.Float(), nullable=False),
    sa.Column('new_odometer', sa.Float(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('odometer_adjustments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_odometer_adjustments_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_odometer_adjustments_vehicle_id'), ['vehicle_id'], unique=False)

    op.create_table('charge_session_tags',
    sa.Column('charge_session_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['charge_session_id'], ['charge_sessions.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('charge_session_id', 'tag_id')
    )
    op.create_table('fuelup_tags',
    sa.Column('fuelup_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fuelup_id'], ['fuelups.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('fuelup_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fuelup_tags')
    op.drop_table('charge_session_tags')
    with op.batch_alter_table('odometer_adjustments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_odometer_adjustments_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_odometer_adjustments_date'))

    op.drop_table('odometer_adjustments')
    with op.batch_alter_table('fuelups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fuelups_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_fuelups_date'))

    op.drop_table('fuelups')
    with op.batch_alter_table('charge_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_charge_sessions_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_charge_sessions_date'))

    op.drop_table('charge_sessions')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_owner_id'))

    op.drop_table('tags')
    # ### end Alembic commands ###
