"""instance settings, driving conditions, user prefs

Revision ID: 8f4beec1bd11
Revises: bc24742df594
Create Date: 2026-07-18 20:57:17.452390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '8f4beec1bd11'
down_revision: Union[str, None] = 'bc24742df594'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instance_settings',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    with op.batch_alter_table('fuelups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('driving_conditions', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'show_driving_conditions',
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('show_driving_conditions')

    with op.batch_alter_table('fuelups', schema=None) as batch_op:
        batch_op.drop_column('driving_conditions')

    op.drop_table('instance_settings')
    # ### end Alembic commands ###
