"""attachments

Revision ID: bc24742df594
Revises: 5aa88876da4e
Create Date: 2026-07-17 19:24:42.841563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = 'bc24742df594'
down_revision: Union[str, None] = '5aa88876da4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_record_id', sa.Integer(), nullable=True),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('stored_name', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['service_record_id'], ['service_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attachments_service_record_id'), ['service_record_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attachments_service_record_id'))

    op.drop_table('attachments')
    # ### end Alembic commands ###
