"""user onboarding flag

Revision ID: f9a623619f9e
Revises: 8f4beec1bd11
Create Date: 2026-07-19 22:28:40.546017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = 'f9a623619f9e'
down_revision: Union[str, None] = '8f4beec1bd11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # existing accounts predate the walkthrough; they get auto-marked done
        # by the app when they already have vehicles
        batch_op.add_column(
            sa.Column(
                'onboarding_done',
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('onboarding_done')

    # ### end Alembic commands ###
